# -*- coding: utf-8 -*-
"""model_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXQDFbWbYWw44A1Yl5um_7g_l7plE0hC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import os
from google.colab import files


# 1. Import dataset from Github
url = "https://raw.githubusercontent.com/AnidaH-git/ml-products_analysis/main/data/cleaned_products.csv"
df = pd.read_csv(url)

# 2. Parse data in column "category_label"
df = df.dropna(subset=["product_title", "category_label"])
df["category_label"] = df["category_label"].str.strip()
# Map all fridge/freezer variations to "Fridge Freezers"
df["category_label"] = df["category_label"].replace({
    "CPUs": "CPU",
    "Freezers": "Fridge Freezers",
    "fridge": "Fridge Freezers",
    "Fridges": "Fridge Freezers",
    "Mobile Phones": "Mobile Phone",
})

# 3. Feature engineering
df["title_length"] = df["product_title"].str.len()

# Features and label (X is properly a 2D DataFrame)
X = df[['product_title', 'title_length']]
y = df["category_label"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Define the Preprocessor (Fixes the NameError)
preprocessor = ColumnTransformer(
    transformers=[
        ("title", TfidfVectorizer(), "product_title"),
        ("length", MinMaxScaler(), ["title_length"])
    ]
)

# 5. Transform the data safely
X_train_tfidf = preprocessor.fit_transform(X_train)
X_test_tfidf = preprocessor.transform(X_test)

# 6. Model selection (Added dual=False to LinearSVC for compatibility)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": MultinomialNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Linear SVC": LinearSVC(dual=False),
    "Random Forest": RandomForestClassifier(random_state=42)
}

# 7. Model training and evaluation
for name, model in models.items():
    # Train the model
    model.fit(X_train_tfidf, y_train)

    # Predict on test data
    y_pred = model.predict(X_test_tfidf)

    # Calculate overall accuracy
    acc = accuracy_score(y_test, y_pred)

    print("=" * 40)
    print(f"MODEL: {name}")
    print(f"Overall Accuracy: {acc:.4f}")
    print("-" * 40)

    # Print precision, recall, and f1-score for each category
    print(classification_report(y_test, y_pred))
    print("=" * 40 + "\n")

"""*Comment:*
Based on the classification reports, the Random Forest model is the best candidate for further testing, closely followed by Linear SVC.

Reasons why Random Forest is the best model option:
1. Highest Overall Performance

- Accuracy: Random Forest achieved the highest overall accuracy at 98% (compared to Linear SVC at 97.84% and Decision Tree at 96.63%).

- Macro Average F1-Score: It is in range between 0.97 and 0.99, showing that it handles performance across all categories evenly without neglecting smaller classes.

2. Superior Handling of Difficult Classes

- The biggest differentiator among these models is how they handle complex, overlapping appliance categories like Dishwashers and Washing Machines:

- Linear SVC has excellent precision for Dishwashers (0.97) but suffers on recall (0.93).

- Random Forest strikes the best balance, achieving a 0.97 precision and 0.96 recall for Dishwashers, and a 0.98 precision and 0.94 recall for Washing Machines. It catches more true instances of these tricky categories than any other model.

3. Balanced Precision and Recall

- While Linear SVC performs exceptionally well on distinct categories like CPUs and Digital Cameras (perfect 1.00 scores), Random Forest matches that near-perfection while maintaining higher, more robust recall scores across the board.

***Random Forest** pipeline is the best model for production or final testing. Because it handles the overlapping terminology between large home appliances better than the linear models, it will be much more robust when making predictions on messy, real-world user search queries or new inventory data.*
"""

# Create the directory if it doesn't exist
os.makedirs("model", exist_ok=True)

# Define preprocessing
preprocessor = ColumnTransformer(
transformers=[
("title", TfidfVectorizer(), "product_title"),
("length", MinMaxScaler(), ["title_length"])
])
# Define pipeline with the best model (e.g. RandomForestClassifier)
pipeline = Pipeline([
("preprocessing", preprocessor),
("classifier", RandomForestClassifier())
])
# Train the model on the entire dataset
pipeline.fit(X, y)

# Save the model to a file
joblib.dump(pipeline, "model/product_model.pkl")
print("Model trained and saved as 'model/product_model.pkl'")

# Browser download of the saved model file
files.download("model/product_model.pkl")