# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fon1uSnCYuZS0dELS3Crq9lPWi1-agN8
"""

import joblib
import pandas as pd
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Load the saved model from Google Drive
model = joblib.load("/content/drive/MyDrive/model/product_model.pkl")
print("Model loaded successfully!")
print("Type 'exit' to stop.\n")

# 3. Use while loop to enter "product_title" for testing
while True:
    product_title = input(" Enter product title: ")
    if product_title.lower() == "exit":
        print("Exiting...")
        break

    # Calculate title length (matching the expected product name)
    title_length = len(product_title)

    # Create a DataFrame with the correct column names
    user_input = pd.DataFrame([{
        "product_title": product_title,
        "title_length": title_length
    }])

    # Predict product category
    prediction = model.predict(user_input)[0]
    print(f" Predicted category: {prediction}\n" + "-" * 40)

"""The model tested product titles from the task. The results were successful, because the model identified correct categories for the products I entered.
However, the model made one mistake. It identified "bosch serie 4 kgv39vl31g as **Dishwasher** category product, instead of **Fridge Freezers**.
- I made my own test using the same name of the product "bosch serie 5 kgv42424po* and the product was correctly categorized as **Fridge Freezers**. This leads to conlusion, that the length of the product title and additional keywords can improve the model classification.
- Samsung 12 64gb was correctly categorized as **Mobile Phones**.
"""